import{useState,useEffect,useRef,useCallback}from"react";import{useNavigate}from"react-router-dom";import{HiArrowLeft,HiCamera,HiPhotograph,HiSearch,HiX,HiUpload,HiShieldCheck,HiExclamation,HiLightningBolt,HiBeaker,HiClipboardList,HiShieldExclamation,HiRefresh}from"react-icons/hi";

const GEMINI_MODEL="gemini-2.0-flash";
const API_URL="https://generativelanguage.googleapis.com/v1beta/models/"+GEMINI_MODEL+":generateContent";

function getApiKey(){try{return localStorage.getItem("nk_gemini_key")||""}catch{return""}}
function setApiKey(k){try{localStorage.setItem("nk_gemini_key",k)}catch{}}

const CROP_PROMPT=`You are a professional agricultural scientist and plant pathologist specializing in Karnataka crops. Analyze the image provided.

If the image is NOT a crop/plant (blurry, animal, person, object, text, indoor scene, vehicle, etc.), respond ONLY with: {"notCrop":true,"reason":"explain briefly why this is not a crop image"}

If the image IS a crop/plant, provide a comprehensive diagnosis in this EXACT JSON format:
{
  "notCrop":false,
  "confidence":<0-100 number>,
  "cropName":"<crop name in English>",
  "cropNameKn":"<crop name in Kannada>",
  "diseaseName":"<disease name if detected, or 'Healthy Plant'>",
  "diseaseNameKn":"<disease name in Kannada, or 'ಆರೋಗ್ಯಕರ ಸಸ್ಯ' if healthy>",
  "symptoms":["<symptom 1>","<symptom 2>","<symptom 3>"],
  "symptomsKn":["<symptom in Kannada 1>","<2>","<3>"],
  "possibleCauses":["<cause 1>","<cause 2>"],
  "possibleCausesKn":["<cause in Kannada 1>","<2>"],
  "recommendedTreatment":["<treatment step 1>","<step 2>","<step 3>"],
  "recommendedTreatmentKn":["<treatment in Kannada 1>","<2>","<3>"],
  "prevention":["<prevention step 1>","<step 2>"],
  "preventionKn":["<prevention in Kannada 1>","<2>"],
  "organicControl":["<organic method 1>","<2>"],
  "organicControlKn":["<organic in Kannada 1>","<2>"],
  "chemicalControl":["<chemical method 1, or 'Not required' if not applicable>"],
  "chemicalControlKn":["<chemical in Kannada 1, or 'ಅಗತ್ಯವಿಲ್ಲ'>"],
  "fertilizerAdvice":"<specific fertilizer recommendations>",
  "fertilizerAdviceKn":"<fertilizer advice in Kannada>",
  "irrigationAdvice":"<specific irrigation advice>",
  "irrigationAdviceKn":"<irrigation advice in Kannada>",
  "severityLevel":"<Low|Medium|High|Critical>",
  "immediateAction":"<what the farmer should do RIGHT NOW>",
  "immediateActionKn":"<immediate action in Kannada>"
}

IMPORTANT RULES:
1. Be SPECIFIC to the visible symptoms in THIS exact image. Never give generic responses.
2. For the SAME crop with DIFFERENT visible symptoms, give DIFFERENT diagnoses.
3. Confidence must reflect how certain you are based on visible evidence.
4. All advice must be evidence-based agricultural science.
5. If the plant appears healthy, say so with diseaseName="Healthy Plant".
6. If symptoms are unclear, lower the confidence score.
7. Respond ONLY with valid JSON, no other text.`;

const TR={en:{title:"Crop AI Doctor",tagline:"AI-Powered Crop Diagnosis",upload:"Upload Image",camera:"Open Camera",gallery:"Choose from Gallery",drag:"or drag and drop image here",analyzing:"Analyzing crop image...",noKey:"API Key Required",noKeyDesc:"Enter your free Gemini API key to enable AI crop analysis. Get a key at aistudio.google.com.",keyLabel:"Gemini API Key",saveKey:"Save Key",keySaved:"Key saved successfully!",search:"Search any crop...",notCrop:"Not a Crop Image",notCropDesc:"The uploaded image does not appear to be a crop or plant. Please upload a clear photo of the affected crop.",confidence:"Confidence",cropName:"Crop",diseaseName:"Disease",symptoms:"Symptoms",causes:"Possible Causes",treatment:"Recommended Treatment",prevention:"Prevention",organic:"Organic Control",chemical:"Chemical Control",fertilizer:"Fertilizer & Nutrients",irrigation:"Irrigation Advice",severity:"Severity Level",immediateAction:"Immediate Action",healthy:"Healthy Plant",error:"Analysis Failed",errorDesc:"Could not analyze the image. Please try again with a clearer photo.",noImage:"No image selected",formats:"Supports JPG, JPEG, PNG, WEBP"},kn:{title:"ಬೆಳೆ AI ವೈದ್ಯ",tagline:"AI-ಚಾಲಿತ ಬೆಳೆ ರೋಗನಿರ್ಣಯ",upload:"ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",camera:"ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ",gallery:"ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ",drag:"ಅಥವಾ ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಎಳೆಯಿರಿ",analyzing:"ಬೆಳೆ ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",noKey:"API ಕೀ ಅಗತ್ಯವಿದೆ",noKeyDesc:"AI ಬೆಳೆ ವಿಶ್ಲೇಷಣೆ ಸಕ್ರಿಯಗೊಳಿಸಲು ನಿಮ್ಮ ಉಚಿತ Gemini API ಕೀ ನಮೂದಿಸಿ. aistudio.google.com ನಲ್ಲಿ ಕೀ ಪಡೆಯಿರಿ.",keyLabel:"Gemini API ಕೀ",saveKey:"ಕೀ ಉಳಿಸಿ",keySaved:"ಕೀ ಉಳಿಸಲಾಗಿದೆ!",search:"ಯಾವುದೇ ಬೆಳೆ ಹುಡುಕಿ...",notCrop:"ಇದು ಬೆಳೆಯ ಚಿತ್ರವಲ್ಲ",notCropDesc:"ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಚಿತ್ರವು ಬೆಳೆ ಅಥವಾ ಸಸ್ಯದಂತೆ ಕಾಣುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ಪೀಡಿತ ಬೆಳೆಯ ಸ್ಪಷ್ಟ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",confidence:"ನಿಖರತೆ",cropName:"ಬೆಳೆ",diseaseName:"ರೋಗ",symptoms:"ಲಕ್ಷಣಗಳು",causes:"ಸಂಭವನೀಯ ಕಾರಣಗಳು",treatment:"ಶಿಫಾರಸು ಚಿಕಿತ್ಸೆ",prevention:"ತಡೆಗಟ್ಟುವಿಕೆ",organic:"ಸಾವಯವ ನಿಯಂತ್ರಣ",chemical:"ರಾಸಾಯನಿಕ ನಿಯಂತ್ರಣ",fertilizer:"ಗೊಬ್ಬರ ಮತ್ತು ಪೋಷಕಾಂಶಗಳು",irrigation:"ನೀರಾವರಿ ಸಲಹೆ",severity:"ತೀವ್ರತೆಯ ಮಟ್ಟ",immediateAction:"ತಕ್ಷಣದ ಕ್ರಮ",healthy:"ಆರೋಗ್ಯಕರ ಸಸ್ಯ",error:"ವಿಶ್ಲೇಷಣೆ ವಿಫಲವಾಗಿದೆ",errorDesc:"ಚಿತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ಪಷ್ಟವಾದ ಫೋಟೋದೊಂದಿಗೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",noImage:"ಯಾವುದೇ ಚಿತ್ರ ಆಯ್ಕೆ ಮಾಡಿಲ್ಲ",formats:"JPG, JPEG, PNG, WEBP ಬೆಂಬಲಿಸುತ್ತದೆ"}};

function fileToBase64(file){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onload=function(){var result=reader.result;var base64=result.split(",")[1];resolve(base64)};reader.onerror=reject;reader.readAsDataURL(file)})}

async function analyzeCropImage(base64Data,mimeType,apiKey){var body={contents:[{parts:[{inlineData:{mimeType:mimeType,data:base64Data}},{text:CROP_PROMPT}]}],generationConfig:{temperature:0.2,maxOutputTokens:2048}};var response=await fetch(API_URL+"?key="+apiKey,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){var err=await response.json().catch(function(){return{}});throw new Error(err.error?err.error.message:"API error "+response.status)}var data=await response.json();var text=data.candidates[0].content.parts[0].text;text=text.replace(/```json\n?/g,"").replace(/```\n?/g,"").trim();try{return JSON.parse(text)}catch(e){var match=text.match(/\{[\s\S]*\}/);if(match){return JSON.parse(match[0])}throw new Error("Could not parse AI response: "+text.substring(0,100))}}

export default function CropDoctor(){var nav=useNavigate();var _l=useState(function(){try{return localStorage.getItem("nk_lang")||"bi"}catch{return"bi"}});var lang=_l[0],setLang=_l[1];var R=function(en,kn){if(lang==="en")return en;if(lang==="kn")return kn;return en+" | "+kn};var _ak=useState(getApiKey);var apiKey=_ak[0],setAk=_ak[1];var _img=useState(null);var img=_img[0],setImg=_img[1];var _pre=useState(null);var preview=_pre[0],setPreview=_pre[1];var _anl=useState(false);var analyzing=_anl[0],setAnalyzing=_anl[1];var _res=useState(null);var result=_res[0],setResult=_res[1];var _err=useState(null);var error=_err[0],setError=_err[1];var _sk=useState(false);var showKey=_sk[0],setShowKey=_sk[1];var _ks=useState("");var keyInput=_ks[0],setKeyInput=_ks[1];var _saved=useState(false);var keySaved=_saved[0],setKeySaved=_saved[1];var fileRef=useRef(null);var cameraRef=useRef(null);var dropRef=useRef(null);useEffect(function(){var h=function(e){setLang(e.detail)};window.addEventListener("langchange",h);return function(){window.removeEventListener("langchange",h)}},[]);

var handleFile=useCallback(async function(file){if(!file)return;if(!["image/jpeg","image/jpg","image/png","image/webp"].includes(file.type)){setError("Invalid format. Use JPG, PNG, or WEBP.");return}setError(null);setResult(null);var url=URL.createObjectURL(file);setPreview(url);setImg(file);setAnalyzing(true);try{var b64=await fileToBase64(file);var data=await analyzeCropImage(b64,file.type,apiKey);setResult(data);setAnalyzing(false)}catch(e){setError(e.message||"Analysis failed");setAnalyzing(false)}},[apiKey]);

var handleDrop=useCallback(function(e){e.preventDefault();var file=e.dataTransfer.files[0];if(file)handleFile(file)},[handleFile]);

var handleKeySave=function(){setAk(keyInput);setApiKey(keyInput);setKeySaved(true);setShowKey(false);setTimeout(function(){setKeySaved(false)},2500)};

var resetAll=function(){setImg(null);setPreview(null);setResult(null);setError(null);setAnalyzing(false)};

var severityColor=function(s){if(s==="Critical"||s==="ತೀವ್ರ")return"bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400";if(s==="High"||s==="ಹೆಚ್ಚು")return"bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400";if(s==="Medium"||s==="ಮಧ್ಯಮ")return"bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400";return"bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400"};

if(!apiKey){return<div className="max-w-2xl mx-auto px-4 py-4"><div className="flex items-center gap-3 mb-4"><button onClick={function(){nav("/")}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100">🌱 {R(TR.en.title,TR.kn.title)}</h1></div><div className="bg-gradient-to-br from-emerald-500 to-green-700 rounded-2xl p-6 text-white shadow-lg mb-4"><h2 className="text-xl font-bold">{R(TR.en.noKey,TR.kn.noKey)}</h2><p className="text-emerald-100 text-sm mt-2">{R(TR.en.noKeyDesc,TR.kn.noKeyDesc)}</p></div><div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border dark:border-gray-700"><label className="text-sm font-bold text-gray-700 dark:text-gray-300 mb-2 block">{R(TR.en.keyLabel,TR.kn.keyLabel)}</label><div className="flex gap-2"><input type="password" value={keyInput} onChange={function(e){setKeyInput(e.target.value)}} placeholder="AIza..." className="flex-1 p-3 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-xl text-sm text-gray-800 dark:text-gray-200"/><button onClick={handleKeySave} className="px-6 py-3 bg-emerald-600 text-white rounded-xl text-sm font-medium hover:bg-emerald-700">{R(TR.en.saveKey,TR.kn.saveKey)}</button></div><p className="text-[10px] text-gray-400 mt-2">Get free key: <a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener" className="text-emerald-600 underline">aistudio.google.com</a></p></div></div>}

return<div className="max-w-2xl mx-auto px-4 py-4"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-3"><button onClick={function(){nav("/")}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><div><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100">🌱 {R(TR.en.title,TR.kn.title)}</h1><p className="text-[10px] text-gray-400">{R(TR.en.tagline,TR.kn.tagline)}</p></div></div><div className="flex items-center gap-2">{preview?<button onClick={resetAll} className="px-3 py-1.5 bg-gray-100 dark:bg-gray-700 rounded-lg text-xs text-gray-600 dark:text-gray-300 flex items-center gap-1"><HiRefresh size={14}/>{R("New","ಹೊಸ")}</button>:null}</div></div>

{!preview?<div ref={dropRef} onDragOver={function(e){e.preventDefault()}} onDrop={handleDrop} className="bg-white dark:bg-gray-800 rounded-2xl p-8 shadow-sm border-2 border-dashed border-gray-200 dark:border-gray-700 text-center hover:border-emerald-400 dark:hover:border-emerald-500 transition-colors"><div className="text-5xl mb-4">📸</div><h3 className="text-lg font-bold text-gray-800 dark:text-gray-100 mb-2">{R(TR.en.upload,TR.kn.upload)}</h3><p className="text-xs text-gray-400 mb-6">{R(TR.en.drag,TR.kn.drag)}</p><div className="flex gap-3 justify-center"><input ref={cameraRef} type="file" accept="image/jpeg,image/jpg,image/png,image/webp" capture="environment" onChange={function(e){handleFile(e.target.files[0])}} className="hidden"/><button onClick={function(){cameraRef.current?cameraRef.current.click():null}} className="flex flex-col items-center gap-2 px-6 py-4 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition-colors"><HiCamera size={24}/><span className="text-xs font-medium">{R(TR.en.camera,TR.kn.camera)}</span></button><input ref={fileRef} type="file" accept="image/jpeg,image/jpg,image/png,image/webp" onChange={function(e){handleFile(e.target.files[0])}} className="hidden"/><button onClick={function(){fileRef.current?fileRef.current.click():null}} className="flex flex-col items-center gap-2 px-6 py-4 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-xl hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"><HiPhotograph size={24}/><span className="text-xs font-medium">{R(TR.en.gallery,TR.kn.gallery)}</span></button></div><p className="text-[10px] text-gray-400 mt-4">{R(TR.en.formats,TR.kn.formats)}</p></div>:<div className="space-y-4">{preview?<div className="relative bg-white dark:bg-gray-800 rounded-2xl overflow-hidden shadow-sm border dark:border-gray-700"><img src={preview} alt="Crop" className="w-full max-h-80 object-contain bg-gray-50 dark:bg-gray-900"/>{analyzing?<div className="absolute inset-0 bg-black/50 flex flex-col items-center justify-center"><div className="w-10 h-10 border-3 border-white border-t-transparent rounded-full animate-spin mb-3"/><p className="text-white text-sm font-medium">{R(TR.en.analyzing,TR.kn.analyzing)}</p></div>:null}</div>:null}

{analyzing?<div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border dark:border-gray-700"><div className="flex items-center gap-3"><div className="w-5 h-5 border-2 border-emerald-600 border-t-transparent rounded-full animate-spin"/><p className="text-sm text-gray-600 dark:text-gray-400">{R(TR.en.analyzing,TR.kn.analyzing)}</p></div></div>:error?<div className="bg-red-50 dark:bg-red-900/30 rounded-xl p-5 border border-red-200 dark:border-red-800"><div className="flex items-center gap-2 mb-2"><HiExclamation className="text-red-500" size={20}/><p className="text-sm font-bold text-red-700 dark:text-red-300">{R(TR.en.error,TR.kn.error)}</p></div><p className="text-sm text-red-600 dark:text-red-400">{error}</p><button onClick={resetAll} className="mt-3 px-4 py-2 bg-red-600 text-white rounded-lg text-sm">Try Again</button></div>:result?result.notCrop?<div className="bg-amber-50 dark:bg-amber-900/30 rounded-xl p-5 border border-amber-200 dark:border-amber-800"><div className="flex items-center gap-2 mb-2"><HiExclamation className="text-amber-500" size={20}/><p className="text-sm font-bold text-amber-700 dark:text-amber-300">{R(TR.en.notCrop,TR.kn.notCrop)}</p></div><p className="text-sm text-amber-600 dark:text-amber-400">{result.reason}</p></div>:<div className="space-y-3"><div className="bg-gradient-to-br from-emerald-500 to-green-700 rounded-2xl p-5 text-white shadow-lg"><div className="flex items-start justify-between"><div><p className="text-emerald-100 text-xs font-medium uppercase tracking-wide">{R(TR.en.cropName,TR.kn.cropName)}</p><h2 className="text-xl font-bold mt-1">{R(result.cropName,result.cropNameKn||result.cropName)}</h2>{result.diseaseName&&result.diseaseName!=="Healthy Plant"?<p className="text-emerald-100 text-sm mt-1">🦠 {R(result.diseaseName,result.diseaseNameKn||result.diseaseName)}</p>:<p className="text-emerald-100 text-sm mt-1">✅ {R(TR.en.healthy,TR.kn.healthy)}</p>}</div><div className="text-right"><div className="bg-white/20 rounded-xl p-3 backdrop-blur-sm"><p className="text-white text-2xl font-bold">{result.confidence}%</p><p className="text-emerald-100 text-[10px]">{R(TR.en.confidence,TR.kn.confidence)}</p></div></div></div><div className="grid grid-cols-2 gap-2">{result.severityLevel?<div className={severityColor(result.severityLevel)+" rounded-xl p-3 text-center"}><p className="text-xs font-bold">{R(TR.en.severity,TR.kn.severity)}</p><p className="text-lg font-bold">{result.severityLevel}</p></div>:null}{result.immediateAction?<div className="bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 rounded-xl p-3"><p className="text-xs font-bold text-red-700 dark:text-red-300 mb-1 flex items-center gap-1"><HiLightningBolt size={14}/>{R(TR.en.immediateAction,TR.kn.immediateAction)}</p><p className="text-xs text-red-600 dark:text-red-400">{R(result.immediateAction,result.immediateActionKn||result.immediateAction)}</p></div>:null}</div></div>

<div className="space-y-3">
{result.symptoms&&result.symptoms.length>0?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">🔍 {R(TR.en.symptoms,TR.kn.symptoms)}</h3><ul className="space-y-1">{result.symptoms.map(function(s,i){return<li key={i} className="text-sm text-gray-600 dark:text-gray-400 pl-4 relative before:content-['•'] before:absolute before:left-0 before:text-emerald-500">{R(s,(result.symptomsKn||[])[i]||s)}</li>})}</ul></div>:null}

{result.possibleCauses&&result.possibleCauses.length>0?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">🧪 {R(TR.en.causes,TR.kn.causes)}</h3><ul className="space-y-1">{result.possibleCauses.map(function(s,i){return<li key={i} className="text-sm text-gray-600 dark:text-gray-400 pl-4 relative before:content-['•'] before:absolute before:left-0 before:text-amber-500">{R(s,(result.possibleCausesKn||[])[i]||s)}</li>})}</ul></div>:null}

{result.recommendedTreatment&&result.recommendedTreatment.length>0?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700 border-l-4 border-l-emerald-500"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">💊 {R(TR.en.treatment,TR.kn.treatment)}</h3><ul className="space-y-1">{result.recommendedTreatment.map(function(s,i){return<li key={i} className="text-sm text-gray-600 dark:text-gray-400 pl-4 relative before:content-['→'] before:absolute before:left-0 before:text-emerald-500">{R(s,(result.recommendedTreatmentKn||[])[i]||s)}</li>})}</ul></div>:null}

<div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
{result.prevention&&result.prevention.length>0?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">🛡️ {R(TR.en.prevention,TR.kn.prevention)}</h3><ul className="space-y-1">{result.prevention.map(function(s,i){return<li key={i} className="text-xs text-gray-600 dark:text-gray-400 pl-3 relative before:content-['•'] before:absolute before:left-0">{R(s,(result.preventionKn||[])[i]||s)}</li>})}</ul></div>:null}

{result.organicControl&&result.organicControl.length>0?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">🌿 {R(TR.en.organic,TR.kn.organic)}</h3><ul className="space-y-1">{result.organicControl.map(function(s,i){return<li key={i} className="text-xs text-gray-600 dark:text-gray-400 pl-3 relative before:content-['•'] before:absolute before:left-0">{R(s,(result.organicControlKn||[])[i]||s)}</li>})}</ul></div>:null}

{result.chemicalControl&&result.chemicalControl.length>0?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">⚗️ {R(TR.en.chemical,TR.kn.chemical)}</h3><ul className="space-y-1">{result.chemicalControl.map(function(s,i){return<li key={i} className="text-xs text-gray-600 dark:text-gray-400 pl-3 relative before:content-['•'] before:absolute before:left-0">{R(s,(result.chemicalControlKn||[])[i]||s)}</li>})}</ul></div>:null}
</div>

{result.fertilizerAdvice?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">🧫 {R(TR.en.fertilizer,TR.kn.fertilizer)}</h3><p className="text-sm text-gray-600 dark:text-gray-400">{R(result.fertilizerAdvice,result.fertilizerAdviceKn||result.fertilizerAdvice)}</p></div>:null}

{result.irrigationAdvice?<div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2 flex items-center gap-1">💧 {R(TR.en.irrigation,TR.kn.irrigation)}</h3><p className="text-sm text-gray-600 dark:text-gray-400">{R(result.irrigationAdvice,result.irrigationAdviceKn||result.irrigationAdvice)}</p></div>:null}
</div></div>:null}</div>}

{apiKey&&!showKey?<button onClick={function(){setShowKey(true)}} className="mt-4 text-[10px] text-gray-400 hover:text-gray-600 w-full text-center">⚙️ Change API Key</button>:null}
{showKey?<div className="mt-4 p-3 bg-white dark:bg-gray-800 rounded-xl border dark:border-gray-700"><div className="flex gap-2"><input type="password" value={keyInput} onChange={function(e){setKeyInput(e.target.value)}} placeholder="AIza..." className="flex-1 p-2 bg-gray-50 dark:bg-gray-700 border dark:border-gray-600 rounded-lg text-xs"/><button onClick={handleKeySave} className="px-3 py-2 bg-emerald-600 text-white rounded-lg text-xs">{R(TR.en.saveKey,TR.kn.saveKey)}</button><button onClick={function(){setShowKey(false);setKeyInput("")}} className="px-3 py-2 bg-gray-200 dark:bg-gray-600 rounded-lg text-xs"><HiX size={14}/></button></div></div>:null}
{keySaved?<p className="text-center text-xs text-emerald-600 mt-2">✅ {R(TR.en.keySaved,TR.kn.keySaved)}</p>:null}</div>}
