import{HiExternalLink}from"react-icons/hi";import{SCHEMES,MACH,CAL,HELPS}from"../data/farmerData.js";
export default function TabsB({tab,R}){
return(<>
{tab==="soil"?<div className="space-y-3"><div className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm"><p className="text-sm font-bold">{R("Karnataka Soil Types","ಕರ್ನಾಟಕ ಮಣ್ಣಿನ ವಿಧಗಳು")}</p><div className="grid grid-cols-2 gap-1.5 mt-2 text-xs">{[{en:"Red",kn:"ಕೆಂಪು"},{en:"Black",kn:"ಕಪ್ಪು"},{en:"Laterite",kn:"ಲ್ಯಾಟರೈಟ್"},{en:"Alluvial",kn:"ಮೆಕ್ಕಲು"},{en:"Coastal",kn:"ಕರಾವಳಿ"},{en:"Forest",kn:"ಅರಣ್ಯ"}].map(function(s,i){return<div key={i} className="bg-gray-50 dark:bg-gray-700/50 rounded p-2"><p className="text-gray-700 dark:text-gray-300">{R(s.en,s.kn)}</p></div>})}</div></div><div className="bg-amber-50 dark:bg-amber-900/20 rounded-xl p-4"><p className="text-sm font-bold text-amber-700 dark:text-amber-300">{R("Soil Health Card","ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್")}</p><p className="text-xs text-amber-600 mt-1">{R("Free soil testing. Visit soilhealth.dac.gov.in","ಉಚಿತ ಮಣ್ಣು ಪರೀಕ್ಷೆ.")}</p></div></div>:null}
{tab==="schemes"?<div className="space-y-2">{SCHEMES.map(function(sc,i){return<div key={i} className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><p className="text-sm font-bold">{R(sc.en,sc.kn)}</p><p className="text-xs text-gray-500">{sc.desc}</p>{sc.url?<a href={sc.url} target="_blank" rel="noopener" className="text-[10px] text-green-600 flex items-center gap-1 mt-1"><HiExternalLink size={10}/>Website</a>:null}</div>})}</div>:null}
{tab==="mach"?<div className="grid grid-cols-2 gap-2">{MACH.map(function(m,i){return<div key={i} className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><p className="text-sm font-bold">🚜 {R(m.en,m.kn)}</p><p className="text-xs text-gray-500 mt-1">{m.d}</p></div>})}</div>:null}
{tab==="cal"?<div className="space-y-2">{CAL.map(function(c){return<div key={c.m} className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><p className="text-sm font-bold text-amber-700 dark:text-amber-300">{R(c.en,c.kn)}</p><p className="text-xs text-gray-600 dark:text-gray-400 mt-1">{c.a}</p></div>})}</div>:null}
{tab==="ai"?<div className="bg-gradient-to-br from-purple-500 to-purple-700 rounded-2xl p-6 text-white shadow-lg"><div className="text-4xl mb-3">🤖</div><h2 className="text-lg font-bold">{R("AI Crop Diagnosis","AI ಬೆಳೆ ರೋಗನಿರ್ಣಯ")}</h2><p className="text-purple-100 text-sm mt-2">{R("Real AI diagnosis after connecting approved AI Vision service.","ಸುರಕ್ಷಿತ AI ವಿಷನ್ ಸೇವೆ ಸಂಪರ್ಕಿಸಿದ ನಂತರ ಲಭ್ಯ.")}</p><p className="text-purple-100 text-xs mt-3 opacity-80">{R("Coming Soon","ಶೀಘ್ರದಲ್ಲೇ")}</p></div>:null}
{tab==="help"?<div className="space-y-2">{HELPS.map(function(h,i){return<div key={i} className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><p className="text-sm font-bold">{R(h.en,h.kn)}</p><div className="flex items-center gap-3 mt-1">{h.p?<a href={"tel:"+h.p.replace(/-/g,"")} className="text-xs text-green-600 font-medium">{h.p}</a>:null}{h.u?<a href={h.u} target="_blank" rel="noopener" className="text-[10px] text-primary-500 flex items-center gap-1"><HiExternalLink size={10}/>Website</a>:null}</div></div>})}</div>:null}
</>);
}