import{useState,useEffect}from"react";import{useNavigate}from"react-router-dom";import{HiArrowLeft,HiBell,HiShieldCheck,HiInformationCircle,HiStar,HiChip,HiLink}from"react-icons/hi";

const T={en:{t:"More",all:"All Services",quick:"Quick Links",info:"Information",notifications:"Notifications",privacy:"Privacy Policy",terms:"Terms & Conditions",rate:"Rate this App",version:"Version 1.0.0",built:"Built with real data APIs for Karnataka",data:"Data Sources: Open-Meteo, rss2json, data.gov.in, OpenStreetMap, ICAR"},kn:{t:"ಇನ್ನಷ್ಟು",all:"ಎಲ್ಲಾ ಸೇವೆಗಳು",quick:"ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",info:"ಮಾಹಿತಿ",notifications:"ಅಧಿಸೂಚನೆಗಳು",privacy:"ಗೌಪ್ಯತಾ ನೀತಿ",terms:"ನಿಯಮಗಳು",rate:"ಅಪ್ಲಿಕೇಶನ್ ರೇಟ್ ಮಾಡಿ",version:"ಆವೃತ್ತಿ ೧.೦.೦",built:"ಕರ್ನಾಟಕಕ್ಕಾಗಿ ನೈಜ ಡೇಟಾ APIಗಳೊಂದಿಗೆ ನಿರ್ಮಿಸಲಾಗಿದೆ",data:"ಡೇಟಾ ಮೂಲಗಳು: Open-Meteo, rss2json, data.gov.in, OpenStreetMap, ICAR"}};

var services=[{t:"Weather",k:"ಹವಾಮಾನ",p:"/weather",e:"🌤️"},{t:"News",k:"ಸುದ್ದಿ",p:"/news",e:"📰"},{t:"Emergency",k:"ತುರ್ತು",p:"/emergency-services",e:"🆘"},{t:"Health",k:"ಆರೋಗ್ಯ",p:"/health",e:"❤️"},{t:"Education",k:"ಶಿಕ್ಷಣ",p:"/education",e:"🎓"},{t:"District Hub",k:"ಜಿಲ್ಲಾ ಕೇಂದ್ರ",p:"/district-hub",e:"🏛️"},{t:"Youth Hub",k:"ಯುವ ಕೇಂದ್ರ",p:"/youth-hub",e:"💡"},{t:"Farmer Hub",k:"ರೈತ ಕೇಂದ್ರ",p:"/farmer-hub",e:"🌾"}];

export default function More(){var n=useNavigate();var s=useState(function(){try{return localStorage.getItem("nk_lang")||"bi"}catch(e){return"bi"}});var l=s[0],sl=s[1];var R=function(en,kn){if(l==="en")return en;if(l==="kn")return kn;return en+" | "+kn};useEffect(function(){var h=function(e){sl(e.detail)};window.addEventListener("langchange",h);return function(){window.removeEventListener("langchange",h)}},[]);

var linkGroups=[{title:R(T.en.all,T.kn.all),items:services},{title:R(T.en.quick,T.kn.quick),items:[{t:"Notifications",k:"ಅಧಿಸೂಚನೆಗಳು",p:"/notifications",e:"🔔"},{t:"Search",k:"ಹುಡುಕಿ",p:"/search",e:"🔍"},{t:"Settings",k:"ಸೆಟ್ಟಿಂಗ್‌ಗಳು",p:"/settings",e:"⚙️"}]},{title:R(T.en.info,T.kn.info),items:[{t:"Privacy Policy",k:"ಗೌಪ್ಯತಾ ನೀತಿ",p:"/privacy",e:"🛡️"},{t:"Terms",k:"ನಿಯಮಗಳು",p:"/terms",e:"📄"}]}];

return<div className="max-w-2xl mx-auto px-4 py-4"><div className="flex items-center gap-3 mb-6"><button onClick={function(){n("/")}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100">{R(T.en.t,T.kn.t)}</h1></div>

{linkGroups.map(function(group,gi){return<div key={gi} className="mb-5"><h3 className="text-xs font-bold text-gray-400 uppercase mb-2 px-1">{group.title}</h3><div className="grid grid-cols-2 gap-2">{group.items.map(function(item,i){return<button key={i} onClick={function(){n(item.p)}} className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700 hover:shadow-md transition-shadow text-left flex items-center gap-3"><span className="text-xl flex-shrink-0">{item.e}</span><span className="text-sm font-medium text-gray-800 dark:text-gray-200">{R(item.t,item.k)}</span></button>})}</div></div>})}

<div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border dark:border-gray-700 text-center"><p className="text-xs text-gray-400">{R(T.en.version,T.kn.version)}</p><p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{R(T.en.built,T.kn.built)}</p><p className="text-[10px] text-gray-400 mt-2">{R(T.en.data,T.kn.data)}</p></div></div>}