import{useState,useEffect}from"react";import{useNavigate}from"react-router-dom";import{HiArrowLeft,HiExternalLink,HiRefresh}from"react-icons/hi";

const FEEDS=[{id:"hindu",en:"The Hindu",kn:"ದಿ ಹಿಂದೂ",url:"https://www.thehindu.com/news/national/karnataka/feeder/default.rss"},{id:"toi",en:"Times of India",kn:"ಟೈಮ್ಸ್ ಆಫ್ ಇಂಡಿಯಾ",url:"https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms"},{id:"prajavani",en:"Prajavani",kn:"ಪ್ರಜಾವಾಣಿ",url:"https://www.prajavani.net/feed"}];
const T={en:{t:"News",ld:"Loading news...",err:"Could not load news. Try again.",rf:"Refresh",src:"Source",read:"Read full article",ago:"ago",min:"min",hr:"hr",d:"d",noNews:"No articles available. Pull to refresh."},kn:{t:"ಸುದ್ದಿ",ld:"ಸುದ್ದಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",err:"ಸುದ್ದಿ ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",rf:"ರಿಫ್ರೆಶ್",src:"ಮೂಲ",read:"ಪೂರ್ಣ ಲೇಖನ ಓದಿ",ago:"ಹಿಂದೆ",min:"ನಿ",hr:"ಗಂ",d:"ದಿ",noNews:"ಯಾವುದೇ ಲೇಖನಗಳಿಲ್ಲ."}};

function timeAgo(d,lg){const ms=Date.now()-new Date(d).getTime();const m=Math.floor(ms/60000);const h=Math.floor(m/60);const da=Math.floor(h/24);const suf=lg==="kn"?T.kn:T.en;if(da>0)return da+suf.d+" "+suf.ago;if(h>0)return h+suf.hr+" "+suf.ago;if(m>0)return m+suf.min+" "+suf.ago;return "1"+suf.min+" "+suf.ago}

async function FF(url){const r=await fetch("https://api.rss2json.com/v1/api.json?rss_url="+encodeURIComponent(url));if(!r.ok)throw Error("fail");const d=await r.json();if(d.status!=="ok")throw Error("api error");return d.items.map(i=>({title:i.title,desc:(i.description||"").replace(/<[^>]*>/g,"").substring(0,200),link:i.link,date:i.pubDate,img:i.thumbnail||i.enclosure?.link||null})).slice(0,15)}

export default function News(){const n=useNavigate();const[l,sl]=useState(()=>{try{return localStorage.getItem("nk_lang")||"bi"}catch{return"bi"}});const R=(en,kn)=>{if(l==="en")return en;if(l==="kn")return kn;return en+" | "+kn};const[feed,sf]=useState(FEEDS[0]);const[arts,sa]=useState([]);const[ld,sld]=useState(true);const[er,ser]=useState(null);useEffect(()=>{const h=e=>sl(e.detail);window.addEventListener("langchange",h);return()=>window.removeEventListener("langchange",h)},[]);useEffect(()=>{load(feed.url)},[feed]);

const load=async(url)=>{sld(true);ser(null);try{const a=await FF(url);sa(a);sld(false)}catch{ser("fetch");sld(false)}};

return<div className="max-w-2xl mx-auto px-4 py-4"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-3"><button onClick={()=>n("/")} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100">{R(T.en.t,T.kn.t)}</h1></div><button onClick={()=>{ser(null);load(feed.url)}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-primary-600"><HiRefresh size={18}/></button></div>

<div className="flex gap-1.5 mb-4 overflow-x-auto scrollbar-none pb-1">{FEEDS.map(f=><button key={f.id} onClick={()=>sf(f)} className={"flex-shrink-0 px-4 py-2 rounded-lg text-sm font-medium transition-all "+(feed.id===f.id?"bg-primary-600 text-white shadow":"bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300 border dark:border-gray-700")}>{R(f.en,f.kn)}</button>)}</div>

{ld?<div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border dark:border-gray-700 text-center"><div className="animate-spin w-8 h-8 border-2 border-primary-600 border-t-transparent rounded-full mx-auto mb-3"/><p className="text-sm text-gray-500">{R(T.en.ld,T.kn.ld)}</p></div>:er?<div className="bg-amber-50 dark:bg-amber-900/30 rounded-xl p-8 text-center"><p className="text-amber-700 dark:text-amber-300 text-sm mb-4">{R(T.en.err,T.kn.err)}</p><button onClick={()=>{ser(null);load(feed.url)}} className="px-4 py-2 bg-primary-600 text-white rounded-lg text-sm font-medium">{R(T.en.rf,T.kn.rf)}</button></div>:arts.length===0?<div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border dark:border-gray-700 text-center"><p className="text-sm text-gray-500">{R(T.en.noNews,T.kn.noNews)}</p></div>:<div className="space-y-3">{arts.map((a,i)=><a key={i} href={a.link} target="_blank" rel="noopener noreferrer" className="block bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700 hover:shadow-md transition-shadow group"><div className="flex gap-3">{a.img?<img src={a.img} alt="" className="w-20 h-20 rounded-lg object-cover flex-shrink-0 bg-gray-100" loading="lazy" onError={e=>{e.target.style.display="none"}}/>:null}<div className="flex-1 min-w-0"><h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100 line-clamp-2 group-hover:text-primary-600 transition-colors">{a.title}</h3><p className="text-xs text-gray-500 dark:text-gray-400 mt-1 line-clamp-2">{a.desc}</p><div className="flex items-center gap-3 mt-2"><span className="text-[10px] text-gray-400">{timeAgo(a.date,l)}</span><span className="text-[10px] text-primary-500 flex items-center gap-0.5"><HiExternalLink size={10}/>{R(T.en.read,T.kn.read)}</span></div></div></div></a>)}</div>}</div>}