import{useState,useEffect}from"react";import{useNavigate}from"react-router-dom";import{HiArrowLeft,HiSun,HiMoon,HiDesktopComputer,HiTrash,HiShieldCheck,HiInformationCircle}from"react-icons/hi";
const T={en:{t:"Settings",theme:"Theme",light:"Light",dark:"Dark",system:"System",language:"Language",en:"English",kn:"ಕನ್ನಡ",bi:"Bilingual",cache:"Storage",clearCache:"Clear Cache",cacheDesc:"Remove cached data and reload",about:"About",appName:"NAMMA KARNATAKA",version:"1.0.0",desc:"Public Services Platform for Karnataka. Real-time weather, news, market prices, emergency services, health, education, and more.",dataSources:"Data Sources",dataList:"Open-Meteo (Weather), rss2json (News), data.gov.in (Market), OpenStreetMap (Hospitals), ICAR/KVK (Crop)",privacy:"Privacy Policy",terms:"Terms"},kn:{t:"ಸೆಟ್ಟಿಂಗ್‌ಗಳು",theme:"ಥೀಮ್",light:"ಬೆಳಕು",dark:"ಡಾರ್ಕ್",system:"ಸಿಸ್ಟಮ್",language:"ಭಾಷೆ",en:"ಇಂಗ್ಲಿಷ್",kn:"ಕನ್ನಡ",bi:"ದ್ವಿಭಾಷಾ",cache:"ಶೇಖರಣೆ",clearCache:"ಶೇಖರಣೆ ಅಳಿಸಿ",cacheDesc:"ಶೇಖರಿಸಿದ ಡೇಟಾ ತೆಗೆದು ಮರುಲೋಡ್",about:"ಬಗ್ಗೆ",appName:"ನಮ್ಮ ಕರ್ನಾಟಕ",version:"೧.೦.೦",desc:"ಕರ್ನಾಟಕ ಸಾರ್ವಜನಿಕ ಸೇವಾ ವೇದಿಕೆ. ನೈಜ-ಸಮಯದ ಹವಾಮಾನ, ಸುದ್ದಿ, ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು, ತುರ್ತು ಸೇವೆಗಳು, ಆರೋಗ್ಯ, ಶಿಕ್ಷಣ ಮತ್ತು ಇನ್ನಷ್ಟು.",dataSources:"ಡೇಟಾ ಮೂಲಗಳು",dataList:"Open-Meteo (ಹವಾಮಾನ), rss2json (ಸುದ್ದಿ), data.gov.in (ಮಾರುಕಟ್ಟೆ), OpenStreetMap (ಆಸ್ಪತ್ರೆ), ICAR/KVK (ಬೆಳೆ)",privacy:"ಗೌಪ್ಯತಾ ನೀತಿ",terms:"ನಿಯಮಗಳು"}};

export default function Settings(){var n=useNavigate();var s=useState(function(){try{return localStorage.getItem("nk_lang")||"bi"}catch(e){return"bi"}});var l=s[0],sl=s[1];var R=function(en,kn){if(l==="en")return en;if(l==="kn")return kn;return en+" | "+kn};var _th=useState(function(){return localStorage.getItem("nk_theme")||"system"});var theme=_th[0],sth=_th[1];var _cl=useState(false);var cleared=_cl[0],scleared=_cl[1];useEffect(function(){var h=function(e){sl(e.detail)};window.addEventListener("langchange",h);return function(){window.removeEventListener("langchange",h)}},[]);

var setTheme=function(t){sth(t);localStorage.setItem("nk_theme",t);if(t==="dark"){document.documentElement.classList.add("dark")}else if(t==="light"){document.documentElement.classList.remove("dark")}else{if(window.matchMedia("(prefers-color-scheme:dark)").matches){document.documentElement.classList.add("dark")}else{document.documentElement.classList.remove("dark")}}};

var clearCache=function(){try{var keys=Object.keys(localStorage);keys.forEach(function(k){if(k.startsWith("nk_")){return}});scleared(true);setTimeout(function(){window.location.reload()},800)}catch(e){scleared(true)}};

return<div className="max-w-2xl mx-auto px-4 py-4"><div className="flex items-center gap-3 mb-6"><button onClick={function(){n("/")}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100">{R(T.en.t,T.kn.t)}</h1></div>

<div className="space-y-4">
<div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-3">{R(T.en.theme,T.kn.theme)}</h3><div className="flex gap-2">{[{v:"light",icon:HiSun,l:"light"},{v:"dark",icon:HiMoon,l:"dark"},{v:"system",icon:HiDesktopComputer,l:"system"}].map(function(o){return<button key={o.v} onClick={function(){setTheme(o.v)}} className={"flex-1 py-3 rounded-xl flex flex-col items-center gap-1 transition-all "+(theme===o.v?"bg-primary-600 text-white shadow":"bg-gray-50 dark:bg-gray-700 text-gray-600 dark:text-gray-400")}><o.icon size={20}/><span className="text-xs font-medium">{R(o.l==="light"?T.en.light:o.l==="dark"?T.en.dark:T.en.system,o.l==="light"?T.kn.light:o.l==="dark"?T.kn.dark:T.kn.system)}</span></button>})}</div></div>

<div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-3">{R(T.en.language,T.kn.language)}</h3><div className="flex gap-2">{[{v:"en",l:R(T.en.en,T.kn.en)},{v:"kn",l:R(T.en.kn,T.kn.kn)},{v:"bi",l:R(T.en.bi,T.kn.bi)}].map(function(o){return<button key={o.v} onClick={function(){sl(o.v);localStorage.setItem("nk_lang",o.v);window.dispatchEvent(new CustomEvent("langchange",{detail:o.v}))}} className={"flex-1 py-3 rounded-xl text-sm font-medium transition-all "+(l===o.v?"bg-primary-600 text-white shadow":"bg-gray-50 dark:bg-gray-700 text-gray-600 dark:text-gray-400")}>{o.l}</button>})}</div></div>

<div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-3">{R(T.en.cache,T.kn.cache)}</h3><p className="text-xs text-gray-500 mb-3">{R(T.en.cacheDesc,T.kn.cacheDesc)}</p><button onClick={clearCache} className="flex items-center gap-2 px-4 py-2 bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400 rounded-lg text-sm font-medium hover:bg-red-100 transition-colors"><HiTrash size={16}/>{cleared?R("Cleared!","ಅಳಿಸಲಾಗಿದೆ!"):R(T.en.clearCache,T.kn.clearCache)}</button></div>

<div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border dark:border-gray-700"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100 mb-2">{R(T.en.about,T.kn.about)}</h3><h2 className="text-lg font-bold text-gray-900 dark:text-gray-100">{R(T.en.appName,T.kn.appName)}</h2><p className="text-xs text-gray-400">v{R(T.en.version,T.kn.version)}</p><p className="text-sm text-gray-600 dark:text-gray-400 mt-2 leading-relaxed">{R(T.en.desc,T.kn.desc)}</p><div className="mt-3 p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg"><p className="text-xs font-medium text-gray-500 dark:text-gray-400">{R(T.en.dataSources,T.kn.dataSources)}</p><p className="text-xs text-gray-400 mt-1">{R(T.en.dataList,T.kn.dataList)}</p></div><div className="flex gap-3 mt-3"><button onClick={function(){n("/privacy")}} className="text-xs text-primary-600 dark:text-primary-400 flex items-center gap-1"><HiShieldCheck size={14}/>{R(T.en.privacy,T.kn.privacy)}</button><button onClick={function(){n("/terms")}} className="text-xs text-primary-600 dark:text-primary-400 flex items-center gap-1"><HiInformationCircle size={14}/>{R(T.en.terms,T.kn.terms)}</button></div></div></div></div>}
