import{useState,useEffect}from"react";import{useNavigate}from"react-router-dom";import{HiArrowLeft,HiSearch,HiX,HiExternalLink,HiRefresh,HiShieldCheck,HiPhone}from"react-icons/hi";import{T,districts,cats,alerts}from"../data/trafficData.js";
export default function Traffic(){var n=useNavigate();var _l=useState(function(){try{return localStorage.getItem("nk_lang")||"bi"}catch(e){return"bi"}});var lg=_l[0],slg=_l[1];var R=function(e,k){if(lg==="en")return e;if(lg==="kn")return k;return e+" | "+k};var _q=useState("");var q=_q[0],sq=_q[1];var _ct=useState("all");var cat=_ct[0],sc=_ct[1];var _di=useState("all");var dist=_di[0],sd=_di[1];useEffect(function(){var h=function(e){slg(e.detail)};window.addEventListener("langchange",h);return function(){window.removeEventListener("langchange",h)}},[]);var filt=alerts.filter(function(a){var ql=q.toLowerCase();var m=a.en.toLowerCase().includes(ql)||a.kn.includes(q)||a.desc.toLowerCase().includes(ql);if(cat!=="all")m=m&&a.cat===cat;if(dist!=="all")m=m&&a.district===dist;return m});var sorted=[].concat(filt).sort(function(a,b){return new Date(b.date)-new Date(a.date)});var showCats=cats.filter(function(c){return c.id==="all"||alerts.some(function(a){return a.cat===c.id})});var showDist=districts.filter(function(d){return d.id==="all"||alerts.some(function(a){return a.district===d.id})});var fmt=function(ds){var d=new Date(ds);return d.toLocaleDateString(lg==="kn"?"kn-IN":"en-IN",{day:"numeric",month:"short",year:"numeric"})};return<div className="max-w-4xl mx-auto px-4 py-4"><div className="flex items-center gap-3 mb-4"><button onClick={function(){n("/")}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><div><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100">🚦 {R(T.en.t,T.kn.t)}</h1><p className="text-[10px] text-gray-400">{R(T.en.st,T.kn.st)}</p></div></div>

<div className="bg-amber-50 dark:bg-amber-900/20 rounded-xl p-3 border border-amber-200 dark:border-amber-800 mb-4"><div className="flex items-center gap-2 text-xs text-amber-700 dark:text-amber-300"><HiShieldCheck size={14}/><span>{R(T.en.noDataMsg,T.kn.noDataMsg)}</span></div><div className="flex gap-3 mt-2 text-[10px] text-amber-600 dark:text-amber-400"><span className="flex items-center gap-1"><HiPhone size={10}/>{R(T.en.nhaHelpline,T.kn.nhaHelpline)}</span><span>{R(T.en.btpHandle,T.kn.btpHandle)}</span></div></div>

<div className="relative mb-3"><HiSearch className="absolute left-3 top-2.5 text-gray-400" size={16}/><input value={q} onChange={function(e){sq(e.target.value)}} placeholder={R(T.en.search,T.kn.search)} className="w-full pl-10 pr-8 py-2.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl text-sm"/>{q?<button onClick={function(){sq("")}} className="absolute right-2 top-2.5 text-gray-400"><HiX size={14}/></button>:null}</div>

<div className="flex gap-1.5 overflow-x-auto pb-2 mb-2">{showCats.map(function(c){return<button key={c.id} onClick={function(){sc(c.id)}} className={"flex-shrink-0 px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap "+(cat===c.id?"bg-primary-600 text-white shadow":"bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300 border dark:border-gray-700")}>{c.icon} {R(c.en,c.kn)}</button>})}</div>

<div className="flex gap-1.5 overflow-x-auto pb-3 mb-2">{showDist.map(function(d){return<button key={d.id} onClick={function(){sd(d.id)}} className={"flex-shrink-0 px-2.5 py-1 rounded-lg text-[11px] font-medium whitespace-nowrap "+(dist===d.id?"bg-amber-500 text-white shadow":"bg-white dark:bg-gray-800 text-gray-500 dark:text-gray-400 border dark:border-gray-700")}>{R(d.en,d.kn)}</button>})}</div>

<div className="flex items-center justify-between mb-3"><p className="text-xs text-gray-400">{sorted.length} {R("alerts","ಎಚ್ಚರಿಕೆಗಳು")} · {R(T.en.lastUpdated,T.kn.lastUpdated)}: {fmt("2026-08-07")}</p><button onClick={function(){window.location.reload()}} className="text-xs text-primary-600 flex items-center gap-1"><HiRefresh size={12}/>{R("Refresh","ರಿಫ್ರೆಶ್")}</button></div>

{sorted.length===0?<div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border dark:border-gray-700 text-center"><div className="text-4xl mb-3">🚦</div><p className="text-gray-500 dark:text-gray-400 font-medium">{R(T.en.noAlerts,T.kn.noAlerts)}</p><p className="text-xs text-gray-400 mt-2">{R(T.en.noDataMsg,T.kn.noDataMsg)}</p></div>
:<div className="space-y-2">{sorted.map(function(a){var catObj=cats.find(function(c){return c.id===a.cat})||{};var distObj=districts.find(function(d){return d.id===a.district})||{};return<div key={a.id} className="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><div className="flex items-start gap-2"><span className="text-xl flex-shrink-0">{catObj.icon||"📋"}</span><div className="flex-1 min-w-0"><div className="flex items-center gap-2 flex-wrap"><h3 className="text-sm font-bold text-gray-800 dark:text-gray-100">{R(a.en,a.kn)}</h3><span className="text-[9px] bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 px-1.5 py-0.5 rounded-full font-medium">{R(T.en.officialSource,T.kn.officialSource)}</span></div><div className="flex items-center gap-2 mt-1"><span className="text-[10px] bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400 px-1.5 py-0.5 rounded">{R(distObj.en,distObj.kn)}</span><span className="text-[10px] text-gray-400">📅 {fmt(a.date)}</span></div><p className="text-xs text-gray-600 dark:text-gray-400 mt-2 leading-relaxed">{R(a.desc,a.descK)}</p><div className="flex items-center justify-between mt-3"><span className="text-[10px] text-gray-400">{a.source}</span><a href={a.url} target="_blank" rel="noopener" className="flex items-center gap-1 text-xs text-primary-600 dark:text-primary-400 font-medium hover:underline"><HiExternalLink size={12}/>{R(T.en.viewSource,T.kn.viewSource)}</a></div></div></div></div>})}</div>}

<div className="mt-4 bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border dark:border-gray-700"><p className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase mb-2">{R(T.en.helplines,T.kn.helplines)}</p><div className="grid grid-cols-2 gap-2 text-xs"><div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-2.5"><p className="text-green-700 dark:text-green-300 font-bold">NHAI 1033</p><p className="text-green-600 dark:text-green-400">24x7 Highway Helpline</p></div><div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-2.5"><p className="text-blue-700 dark:text-blue-300 font-bold">BBMP</p><p className="text-blue-600 dark:text-blue-400">080-22975936</p></div><div className="bg-orange-50 dark:bg-orange-900/20 rounded-lg p-2.5"><p className="text-orange-700 dark:text-orange-300 font-bold">PWD</p><p className="text-orange-600 dark:text-orange-400">080-22249981</p></div><div className="bg-purple-50 dark:bg-purple-900/20 rounded-lg p-2.5"><p className="text-purple-700 dark:text-purple-300 font-bold">KSHIP</p><p className="text-purple-600 dark:text-purple-400">kship.in</p></div></div></div></div>}