import{useState,useEffect,useRef}from"react";import{useNavigate}from"react-router-dom";import{HiArrowLeft,HiLocationMarker,HiRefresh,HiSearch,HiX}from"react-icons/hi";

const CITIES=[{en:"Bengaluru",kn:"ಬೆಂಗಳೂರು",lat:12.9716,lon:77.5946},{en:"Mysuru",kn:"ಮೈಸೂರು",lat:12.2958,lon:76.6394},{en:"Hubballi",kn:"ಹುಬ್ಬಳ್ಳಿ",lat:15.3647,lon:75.1240},{en:"Mangaluru",kn:"ಮಂಗಳೂರು",lat:12.9141,lon:74.8560},{en:"Belagavi",kn:"ಬೆಳಗಾವಿ",lat:15.8497,lon:74.4977},{en:"Davanagere",kn:"ದಾವಣಗೆರೆ",lat:14.4644,lon:75.9218},{en:"Ballari",kn:"ಬಳ್ಳಾರಿ",lat:15.1394,lon:76.9214},{en:"Kalaburagi",kn:"ಕಲಬುರಗಿ",lat:17.3297,lon:76.8343},{en:"Shivamogga",kn:"ಶಿವಮೊಗ್ಗ",lat:13.9299,lon:75.5681},{en:"Tumakuru",kn:"ತುಮಕೂರು",lat:13.3379,lon:77.1173},{en:"Udupi",kn:"ಉಡುಪಿ",lat:13.3409,lon:74.7421},{en:"Raichur",kn:"ರಾಯಚೂರು",lat:16.2076,lon:77.3463},{en:"Hassan",kn:"ಹಾಸನ",lat:13.0068,lon:76.0996},{en:"Bidar",kn:"ಬೀದರ್",lat:17.9134,lon:77.5193},{en:"Mandya",kn:"ಮಂಡ್ಯ",lat:12.5222,lon:76.9005},{en:"Kolar",kn:"ಕೋಲಾರ",lat:13.1367,lon:78.1294},{en:"Karwar",kn:"ಕಾರವಾರ",lat:14.8017,lon:74.1299},{en:"Madikeri",kn:"ಮಡಿಕೇರಿ",lat:12.4244,lon:75.7382},{en:"Chitradurga",kn:"ಚಿತ್ರದುರ್ಗ",lat:14.2306,lon:76.3985},{en:"Bagalkot",kn:"ಬಾಗಲಕೋಟೆ",lat:16.1843,lon:75.6989},{en:"Vijayapura",kn:"ವಿಜಯಪುರ",lat:16.8302,lon:75.7100},{en:"Haveri",kn:"ಹಾವೇರಿ",lat:14.7933,lon:75.4033},{en:"Koppal",kn:"ಕೊಪ್ಪಳ",lat:15.3494,lon:76.1486},{en:"Ramanagara",kn:"ರಾಮನಗರ",lat:12.7174,lon:77.2859},{en:"Chikkamagaluru",kn:"ಚಿಕ್ಕಮಗಳೂರು",lat:13.3159,lon:75.7754},{en:"Dharwad",kn:"ಧಾರವಾಡ",lat:15.4589,lon:75.0078},{en:"Sirsi",kn:"ಶಿರಸಿ",lat:14.6204,lon:74.8341},{en:"Chamarajanagar",kn:"ಚಾಮರಾಜನಗರ",lat:11.9235,lon:76.9415}];

const WC={"0":"☀️ Clear","1":"🌤️ Mainly Clear","2":"⛅ Partly Cloudy","3":"☁️ Overcast","45":"🌫️ Fog","48":"🌫️ Fog","51":"🌧️ Drizzle","53":"🌧️ Drizzle","55":"🌧️ Drizzle","61":"🌧️ Light Rain","63":"🌧️ Rain","65":"🌧️ Heavy Rain","71":"❄️ Light Snow","73":"❄️ Snow","75":"❄️ Heavy Snow","80":"🌧️ Showers","81":"🌧️ Heavy Showers","82":"🌧️ Violent Showers","95":"⚡ Thunderstorm","96":"⚡ Hail Storm","99":"⚡ Severe Storm"};
const WCK={"0":"ಸ್ಪಷ್ಟ ಆಕಾಶ","1":"ಬಹುತೇಕ ಸ್ಪಷ್ಟ","2":"ಭಾಗಶಃ ಮೋಡ","3":"ಮೋಡ ಕವಿದ","45":"ಮಂಜು","48":"ಮಂಜು","51":"ತುಂತುರು","53":"ತುಂತುರು","55":"ಜೋರು ತುಂತುರು","61":"ಲಘು ಮಳೆ","63":"ಮಳೆ","65":"ಭಾರಿ ಮಳೆ","71":"ಲಘು ಹಿಮ","73":"ಹಿಮಪಾತ","75":"ಭಾರಿ ಹಿಮ","80":"ಮಳೆ ಸುರಿಮಳೆ","81":"ಭಾರಿ ಸುರಿಮಳೆ","82":"ಅತಿ ಭಾರಿ ಸುರಿಮಳೆ","95":"ಗುಡುಗು ಸಿಡಿಲು","96":"ಆಲಿಕಲ್ಲು","99":"ತೀವ್ರ ಗುಡುಗು"};

const TR={en:{title:"Weather",loading:"Loading weather data...",noLocation:"Location access denied or unavailable. Please select a city below or enable location in browser settings.",searchCity:"Search city...",refresh:"Refresh",feelsLike:"Feels like",humidity:"Humidity",wind:"Wind",forecast:"7-Day Forecast",selectCity:"Select a city"},kn:{title:"ಹವಾಮಾನ",loading:"ಹವಾಮಾನ ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",noLocation:"ಸ್ಥಳ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ ಅಥವಾ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಕೆಳಗಿನ ನಗರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಅಥವಾ ಬ್ರೌಸರ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಸ್ಥಳ ಸಕ್ರಿಯಗೊಳಿಸಿ.",searchCity:"ನಗರ ಹುಡುಕಿ...",refresh:"ರಿಫ್ರೆಶ್",feelsLike:"ಅನುಭವಿಸುವ ತಾಪಮಾನ",humidity:"ಆರ್ದ್ರತೆ",wind:"ಗಾಳಿ",forecast:"7-ದಿನ ಮುನ್ಸೂಚನೆ",selectCity:"ನಗರ ಆಯ್ಕೆಮಾಡಿ"}};

async function fetchWeather(lat,lon){const url="https://api.open-meteo.com/v1/forecast?latitude="+lat+"&longitude="+lon+"&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code,apparent_temperature&daily=temperature_2m_max,temperature_2m_min,weather_code&timezone=Asia/Kolkata&forecast_days=7";const res=await fetch(url);if(!res.ok)throw new Error("API error "+res.status);return await res.json()}

export default function Weather(){const nav=useNavigate();const[lang,setLang]=useState(()=>{try{return localStorage.getItem("nk_lang")||"bi"}catch{return"bi"}});const R=(en,kn)=>{if(lang==="en")return en;if(lang==="kn")return kn;return en+" | "+kn};const[weather,setWeather]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState(null);const[city,setCity]=useState(null);const[search,setSearch]=useState("");const[forecast,setForecast]=useState([]);const[showDropdown,setShowDropdown]=useState(false);const searchRef=useRef(null);

useEffect(()=>{const handler=e=>setLang(e.detail);window.addEventListener("langchange",handler);return()=>window.removeEventListener("langchange",handler)},[]);
useEffect(()=>{detectLocation()},[]);

const detectLocation=async()=>{setLoading(true);setError(null);if(!navigator.geolocation){setError("unavailable");setLoading(false);return}try{const pos=await new Promise((resolve,reject)=>{navigator.geolocation.getCurrentPosition(resolve,reject,{timeout:10000,maximumAge:600000,enableHighAccuracy:false})});let nearest=null,minDist=Infinity;for(const c of CITIES){const dist=Math.hypot(c.lat-pos.coords.latitude,c.lon-pos.coords.longitude);if(dist<minDist){minDist=dist;nearest=c}}setCity(nearest);await loadWeather(nearest.lat,nearest.lon);setShowDropdown(false)}catch{setError("denied");setLoading(false)}};

const loadWeather=async(lat,lon)=>{setLoading(true);setError(null);try{const data=await fetchWeather(lat,lon);setWeather(data.current);setForecast(data.daily.time.map((t,i)=>({date:t,hi:data.daily.temperature_2m_max[i],lo:data.daily.temperature_2m_min[i],code:String(data.daily.weather_code[i])})));setLoading(false)}catch{setError("fetch");setLoading(false)}};

const selectCity=async(c)=>{setCity(c);setSearch("");setShowDropdown(false);await loadWeather(c.lat,c.lon)};

const filtered=CITIES.filter(c=>{const q=search.toLowerCase().trim();if(!q)return false;return c.en.toLowerCase().includes(q)||c.kn.includes(search)});

return<div className="max-w-2xl mx-auto px-4 py-4"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-3"><button onClick={()=>nav("/")} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100">{R(TR.en.title,TR.kn.title)}</h1></div><div className="flex items-center gap-2"><button onClick={()=>{if(city)loadWeather(city.lat,city.lon);else detectLocation()}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-primary-600" title={R(TR.en.refresh,TR.kn.refresh)}><HiRefresh size={18}/></button><button onClick={detectLocation} className="w-9 h-9 rounded-lg bg-primary-50 dark:bg-primary-900/30 flex items-center justify-center text-primary-600" title="Use my location"><HiLocationMarker size={18}/></button></div></div>

<div className="relative mb-4"><HiSearch className="absolute left-3 top-2.5 text-gray-400" size={16}/><input ref={searchRef} value={search} onChange={e=>{setSearch(e.target.value);setShowDropdown(true)}} onFocus={()=>setShowDropdown(true)} placeholder={R(TR.en.searchCity,TR.kn.searchCity)} className="w-full pl-10 pr-8 py-2.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500/20 text-gray-800 dark:text-gray-200"/>{search?<button onClick={()=>{setSearch("");setShowDropdown(false)}} className="absolute right-2 top-2.5 text-gray-400"><HiX size={14}/></button>:null}{showDropdown&&filtered.length>0&&search?<div className="absolute top-full mt-1 left-0 right-0 bg-white dark:bg-gray-800 rounded-xl shadow-lg border dark:border-gray-700 max-h-60 overflow-y-auto z-50">{filtered.slice(0,10).map((c,i)=><button key={i} onClick={()=>selectCity(c)} className="w-full text-left px-4 py-2.5 text-sm hover:bg-gray-50 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 flex items-center gap-2"><HiLocationMarker size={14} className="text-primary-500 flex-shrink-0"/><span>{R(c.en,c.kn)}</span></button>)}</div>:null}</div>

{loading?<div className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border dark:border-gray-700 flex flex-col items-center justify-center" style={{minHeight:"200px"}}><div className="w-8 h-8 border-2 border-primary-600 border-t-transparent rounded-full animate-spin mb-3"/><p className="text-sm text-gray-500 dark:text-gray-400">{R(TR.en.loading,TR.kn.loading)}</p></div>:error?<div className="bg-amber-50 dark:bg-amber-900/30 rounded-xl p-5 border border-amber-200 dark:border-amber-800"><p className="text-amber-800 dark:text-amber-200 text-sm mb-3">{R(TR.en.noLocation,TR.kn.noLocation)}</p><div className="flex flex-wrap gap-2">{CITIES.slice(0,8).map((c,i)=><button key={i} onClick={()=>selectCity(c)} className="px-3 py-1.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg text-xs text-gray-700 dark:text-gray-300 hover:border-primary-300 transition-colors">{R(c.en,c.kn)}</button>)}</div></div>:weather?<div className="space-y-3"><div className="bg-gradient-to-br from-sky-500 to-blue-600 rounded-2xl p-5 text-white shadow-lg"><div className="flex items-start justify-between"><div><p className="text-sky-100 text-sm font-medium">{city?R(city.en,city.kn):""}</p><p className="text-5xl font-bold mt-1">{Math.round(weather.temperature_2m)}<span className="text-xl font-normal">°C</span></p><p className="text-sky-100 text-sm mt-1">{R(WC[String(weather.weather_code)]||"🌡️ Unknown",WCK[String(weather.weather_code)]||"ಗೊತ್ತಿಲ್ಲ")}</p><p className="text-sky-200 text-xs mt-0.5">{R(TR.en.feelsLike,TR.kn.feelsLike)}: {Math.round(weather.apparent_temperature)}°C</p></div><div className="text-5xl">{WC[String(weather.weather_code)]?WC[String(weather.weather_code)].split(" ")[0]:"🌡️"}</div></div><div className="grid grid-cols-2 gap-3 mt-3"><div className="bg-white/20 rounded-xl p-3 backdrop-blur-sm"><p className="text-xs text-sky-100">{R(TR.en.humidity,TR.kn.humidity)}</p><p className="text-xl font-bold">{weather.relative_humidity_2m}%</p></div><div className="bg-white/20 rounded-xl p-3 backdrop-blur-sm"><p className="text-xs text-sky-100">{R(TR.en.wind,TR.kn.wind)}</p><p className="text-xl font-bold">{Math.round(weather.wind_speed_10m)} km/h</p></div></div></div>

{forecast.length>0?<div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border dark:border-gray-700"><h3 className="font-bold text-gray-800 dark:text-gray-100 mb-3">{R(TR.en.forecast,TR.kn.forecast)}</h3><div className="space-y-1">{forecast.map((d,i)=><div key={i} className="flex items-center justify-between p-2 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700/50"><span className="text-2xl w-9 text-center">{WC[d.code]?WC[d.code].split(" ")[0]:"☀️"}</span><span className="flex-1 ml-3 text-sm font-medium text-gray-700 dark:text-gray-300">{new Date(d.date).toLocaleDateString(lang==="kn"?"kn-IN":"en-IN",{weekday:"long",day:"numeric",month:"short"})}</span><div className="flex gap-3 text-sm"><span className="text-gray-800 dark:text-gray-200 font-medium">{Math.round(d.hi)}°</span><span className="text-gray-400 dark:text-gray-500">{Math.round(d.lo)}°</span></div></div>)}</div></div>:null}</div>:null}

{city||loading?null:<div className="mt-4"><h3 className="text-sm font-bold text-gray-500 dark:text-gray-400 mb-2">{R(TR.en.selectCity,TR.kn.selectCity)}</h3><div className="flex flex-wrap gap-1.5">{CITIES.map((c,i)=><button key={i} onClick={()=>selectCity(c)} className="px-2.5 py-1 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg text-xs text-gray-600 dark:text-gray-300 hover:border-primary-300 transition-colors">{R(c.en,c.kn)}</button>)}</div></div>}</div>}
