import{useState,useEffect}from"react";import{useNavigate}from"react-router-dom";import{HiArrowLeft,HiExternalLink,HiRefresh,HiLightBulb}from"react-icons/hi";

const FEEDS=[{id:"emp",en:"Employment News",kn:"ಉದ್ಯೋಗ ಸುದ್ದಿ",url:"https://www.employmentnews.gov.in/feed"},{id:"career",en:"Career Tips",kn:"ವೃತ್ತಿ ಸಲಹೆ",url:"https://timesofindia.indiatimes.com/rssfeeds/913168846.cms"}];
const LINKS=[{en:"UPSC - Civil Services",kn:"UPSC - ನಾಗರಿಕ ಸೇವೆಗಳು",url:"https://www.upsc.gov.in",d:"Union Public Service Commission",dk:"ಕೇಂದ್ರ ಲೋಕಸೇವಾ ಆಯೋಗ"},{en:"KPSC - Karnataka",kn:"KPSC - ಕರ್ನಾಟಕ",url:"https://kpsc.kar.nic.in",d:"Karnataka Public Service Commission",dk:"ಕರ್ನಾಟಕ ಲೋಕಸೇವಾ ಆಯೋಗ"},{en:"NCS Career Portal",kn:"NCS ವೃತ್ತಿ ಪೋರ್ಟಲ್",url:"https://www.ncs.gov.in",d:"National Career Service - jobs & guidance",dk:"ರಾಷ್ಟ್ರೀಯ ವೃತ್ತಿ ಸೇವೆ - ಉದ್ಯೋಗ ಮತ್ತು ಮಾರ್ಗದರ್ಶನ"},{en:"Skill India",kn:"ಸ್ಕಿಲ್ ಇಂಡಿಯಾ",url:"https://www.skillindia.gov.in",d:"Free skill development courses",dk:"ಉಚಿತ ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಕೋರ್ಸ್‌ಗಳು"},{en:"Employment News (e-Paper)",kn:"ಉದ್ಯೋಗ ಸಮಾಚಾರ",url:"https://www.employmentnews.gov.in",d:"Govt job notifications weekly",dk:"ಸರ್ಕಾರಿ ಉದ್ಯೋಗ ಅಧಿಸೂಚನೆಗಳು"},{en:"Startup India",kn:"ಸ್ಟಾರ್ಟ್‌ಅಪ್ ಇಂಡಿಯಾ",url:"https://www.startupindia.gov.in",d:"Entrepreneurship & startup support",dk:"ಉದ್ಯಮಶೀಲತೆ & ಸ್ಟಾರ್ಟ್‌ಅಪ್ ಬೆಂಬಲ"}];
const T={en:{t:"Youth Hub",news:"Latest Updates",ld:"Loading...",err:"Could not load updates.",rf:"Refresh",portals:"Official Career Portals",read:"Open"},kn:{t:"ಯುವ ಕೇಂದ್ರ",news:"ಇತ್ತೀಚಿನ ನವೀಕರಣಗಳು",ld:"ಲೋಡ್ ಆಗುತ್ತಿದೆ...",err:"ನವೀಕರಣಗಳು ಲೋಡ್ ಆಗಲಿಲ್ಲ.",rf:"ರಿಫ್ರೆಶ್",portals:"ಅಧಿಕೃತ ವೃತ್ತಿ ಪೋರ್ಟಲ್‌ಗಳು",read:"ತೆರೆಯಿರಿ"}};

async function FF(url){var r=await fetch("https://api.rss2json.com/v1/api.json?rss_url="+encodeURIComponent(url));var d=await r.json();if(d.status!=="ok")throw Error("fail");return d.items.map(function(i){var desc=(i.description||"").replace(/<[^>]*>/g,"").substring(0,160);return{title:i.title,desc:desc,link:i.link,date:i.pubDate}}).slice(0,10)}

function timeAgo(dt,lg){var ms=Date.now()-new Date(dt).getTime();var m=Math.floor(ms/60000);var h=Math.floor(m/60);var da=Math.floor(h/24);if(da>0)return da+(lg==="kn"?"ದಿ":"d");if(h>0)return h+(lg==="kn"?"ಗಂ":"h");return(m||1)+(lg==="kn"?"ನಿ":"m")}

export default function YouthHub(){var n=useNavigate();var s=useState(function(){try{return localStorage.getItem("nk_lang")||"bi"}catch(e){return"bi"}});var l=s[0],sl=s[1];var R=function(en,kn){if(l==="en")return en;if(l==="kn")return kn;return en+" | "+kn};var _s2=useState(FEEDS[0]);var feed=_s2[0],sf=_s2[1];var _s3=useState([]);var arts=_s3[0],sa=_s3[1];var _s4=useState(true);var ld=_s4[0],sld=_s4[1];var _s5=useState(null);var er=_s5[0],ser=_s5[1];useEffect(function(){var h=function(e){sl(e.detail)};window.addEventListener("langchange",h);return function(){window.removeEventListener("langchange",h)}},[]);useEffect(function(){load(feed.url)},[feed]);

var load=async function(url){sld(true);ser(null);try{var a=await FF(url);sa(a);sld(false)}catch(e){ser("fetch");sld(false)}};

return<div className="max-w-2xl mx-auto px-4 py-4"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-3"><button onClick={function(){n("/")}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-gray-500"><HiArrowLeft size={18}/></button><h1 className="text-lg font-bold text-gray-800 dark:text-gray-100"><HiLightBulb className="inline text-orange-500 mr-1" size={20}/>{R(T.en.t,T.kn.t)}</h1></div><button onClick={function(){ser(null);load(feed.url)}} className="w-9 h-9 rounded-lg bg-white dark:bg-gray-800 shadow-sm border dark:border-gray-700 flex items-center justify-center text-primary-600"><HiRefresh size={18}/></button></div>

<h3 className="text-sm font-bold text-gray-500 dark:text-gray-400 uppercase mb-3">{R(T.en.portals,T.kn.portals)}</h3>
<div className="grid grid-cols-2 gap-2 mb-4">{LINKS.map(function(li,i){return<a key={i} href={li.url} target="_blank" rel="noopener" className="block bg-white dark:bg-gray-800 rounded-xl p-3 shadow-sm border dark:border-gray-700 hover:shadow-md transition-shadow"><p className="text-xs font-semibold text-gray-800 dark:text-gray-100">{R(li.en,li.kn)}</p><p className="text-[10px] text-gray-400 mt-0.5">{R(li.d,li.dk)}</p></a>})}</div>

<h3 className="text-sm font-bold text-gray-500 dark:text-gray-400 uppercase mb-3">{R(T.en.news,T.kn.news)}</h3>
<div className="flex gap-1.5 mb-4 overflow-x-auto scrollbar-none pb-1">{FEEDS.map(function(f){return<button key={f.id} onClick={function(){sf(f)}} className={"flex-shrink-0 px-4 py-2 rounded-lg text-sm font-medium transition-all "+(feed.id===f.id?"bg-orange-600 text-white shadow":"bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300 border dark:border-gray-700")}>{R(f.en,f.kn)}</button>})}</div>

{ld?<div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border dark:border-gray-700 text-center"><div className="animate-spin w-8 h-8 border-2 border-orange-600 border-t-transparent rounded-full mx-auto mb-3"/><p className="text-sm text-gray-500">{R(T.en.ld,T.kn.ld)}</p></div>:er?<div className="bg-amber-50 dark:bg-amber-900/30 rounded-xl p-8 text-center"><p className="text-amber-700 dark:text-amber-300 text-sm mb-4">{R(T.en.err,T.kn.err)}</p><button onClick={function(){ser(null);load(feed.url)}} className="px-4 py-2 bg-orange-600 text-white rounded-lg text-sm font-medium">{R(T.en.rf,T.kn.rf)}</button></div>:arts.length===0?<div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-sm border dark:border-gray-700 text-center"><p className="text-sm text-gray-500">No articles</p></div>:<div className="space-y-2">{arts.map(function(a,i){return<a key={i} href={a.link} target="_blank" rel="noopener" className="block bg-white dark:bg-gray-800 rounded-xl p-3 shadow-sm border dark:border-gray-700 hover:shadow-md transition-shadow"><div className="flex items-start justify-between gap-2"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-gray-800 dark:text-gray-100 line-clamp-2">{a.title}</p><p className="text-[11px] text-gray-500 mt-0.5 line-clamp-1">{a.desc}</p></div><span className="text-[10px] text-gray-400 flex-shrink-0">{timeAgo(a.date,l)}</span></div></a>})}</div>}</div>}